---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  environment: "{{proxy_env}}"
  tasks:
   - name: first try to fix missing GPG keys apt repository errors (NO_PUBKEY)
     shell: >
       apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=\("$key"\); fi; done
     ignore_errors: True
   - name: second try to fix missing GPG keys apt repository errors (NO_PUBKEY)
     shell: >
       apt update 2>&1 1>/dev/null | sed -ne 's/.*NO_PUBKEY //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys "$key"; keys+=\("$key"\); fi; done
     ignore_errors: True
   - name: first try to fix expired GPG keys apt repository errors (EXPKEYSIG)
     shell: >
       apt update 2>&1 1>/dev/null | sed -ne 's/.*EXPKEYSIG //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then apt-key adv --keyserver hkp://pool.sks-keyservers.net:80 --recv-keys "$key"; keys+=\("$key"\); fi; done
     ignore_errors: True
   - name: second try to fix expired GPG keys apt repository errors (EXPKEYSIG)
     shell: >
       apt update 2>&1 1>/dev/null | sed -ne 's/.*EXPKEYSIG //p' | while read key; do if ! [[ ${keys[*]} =~ "$key" ]]; then apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-keys "$key"; keys+=\("$key"\); fi; done
     ignore_errors: True
   - name: fix install errors
     command: "dpkg --configure -a"
     ignore_errors: true
   - block:
       - name: update APT
         command: apt update
     rescue:
       - name: update APT (with apt-get)
         apt:
           update_cache: yes
         ignore_errors: True
   - block:
       - name: upgrade APT (with expect)
         expect:
           command: apt upgrade -y
           responses:
             Y/I/N/O/D/Z: "Y"
     rescue:
       - block:
           - name: upgrade APT
             command: apt upgrade -y
         rescue:
           - name: dpkg --configure -a
             command: dpkg --configure -a
             ignore_errors: True
           - name: apt install -f
             command: apt install -f -y
             ignore_errors: True
   - name: autoremove APT
     command: apt autoremove --purge -y
   - name: autoclean APT
     command: apt autoclean -y
   - name: clean APT
     command: apt clean -y
