---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  environment: "{{proxy_env}}"
  tasks:
    - name: add several apt repositories
      include_tasks: add_repo.yml
      loop:
        - { name : 'google-chrome', key_url: 'https://dl.google.com/linux/linux_signing_key.pub', repo: '[arch={{ arch_deb }}] http://dl.google.com/linux/chrome/deb/ stable main' }
        - { name : 'atom', key_url: 'https://packagecloud.io/AtomEditor/atom/gpgkey', repo: '[arch={{ arch_deb }}] https://packagecloud.io/AtomEditor/atom/any/ any main' }
        - { name : 'docker', key_url: 'https://download.docker.com/linux/ubuntu/gpg', repo: '[arch={{ arch_deb }}] https://download.docker.com/linux/ubuntu {{ dist_deb }} stable' }
        - { name : 'sublime-text', key_url: 'https://download.sublimetext.com/sublimehq-pub.gpg', repo: 'https://download.sublimetext.com/ apt/dev/' }
        - { name : 'geogebra', key_url: 'https://static.geogebra.org/linux/office@geogebra.org.gpg.key', repo: '[arch={{ arch_deb }}] http://www.geogebra.net/linux/ stable main' }
        - { name : 'virtualbox', key_url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc', repo: '[arch={{ arch_deb }}] https://download.virtualbox.org/virtualbox/debian {{ dist_deb }} contrib' }
      loop_control:
        loop_var: repository

    - block:
        - name: add a signing key for R-Project repository
          apt_key:
            keyserver: keyserver.ubuntu.com
            id: E298A3A825C0D65DFD57CBB651716619E084DAB9
        - name: add repository R-Project
          apt_repository:
            repo: deb https://cloud.r-project.org/bin/linux/ubuntu {{ dist_deb }}-cran35/
            state: present
            filename: r-project
      ignore_errors: True

    - block:
        - name: update APT
          command: apt update
      rescue:
        - name: update APT (with apt-get)
          apt:
            update_cache: yes
          ignore_errors: True
