---
- hosts: labDTL
  become: true
  vars_files:
    - vars.yml
  environment: "{{proxy_env}}"
  tasks:
   - name: install LibreOffice
     command: apt install -y libreoffice mythes-en-us libreoffice-l10n-pt-br
   - name: install Thunderbird
     command: apt install -y thunderbird thunderbird-locale-en 
   - name: install compressing
     command: apt install -y unrar pbzip2
   - name: install Firefox
     command: apt install -y firefox firefox-locale-en firefox-locale-pt
   - name: install Google-Chrome
     command: apt install -y google-chrome-stable
   - name: install Flash Plugin
     command: apt install -y flashplugin-installer
   - name: install PDF-PC
     command: apt install -y pdf-presenter-console
   - name: install VirtualBox
     command: apt install -y virtualbox
   - name: install additional packages with languages
     command: apt install -y libreoffice-help-{{ item.lang }} hyphen-{{ item.lang }} thunderbird-locale-{{ item.lang }}
     with_items:
       - { lang: 'en-us' }
       - { lang: 'pt-br' }

