---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  environment: "{{proxy_env}}"
  tasks:
   - name: install gcc
     command: apt install -y gcc g++
   - name: install Fortran
     command: apt install -y gfortran
   - name: install OpenBLAS
     command: apt install -y libopenblas-dev
   - name: install Python
     command: apt install -y python python3
   - name: install essential modules from Python
     command: apt install -y python-"{{ item }}" python3-"{{ item }}"
     loop:
       - dev
       - pip
       - pexpect
   - name: install essential modules in Python with pip
     shell: pip install "{{ item }}" && pip3 install "{{ item }}"
     loop:
       - virtualenv
   - name: install Java
     command: apt install -y default-jdk
   - name: install Maven
     command: apt install -y maven
   - name: install Git
     command: apt install -y git
   - name: install GNU-Plot
     command: apt install -y gnuplot
   - name: install Octave
     command: apt install -y octave
   - name: install SWI-Prolog
     command: apt install -y swi-prolog
   - name: install Gimp
     command: apt install -y gimp
   - name: install Apache2-httpd
     command: apt install -y apache2
   - name: install PHP
     command: apt install -y php libapache2-mod-php php-mysql
   - name: remove old versions of Docker
     command: apt remove -y docker docker-engine docker.io
   - name: install Docker
     command: apt install -y docker.io #docker-ce
     ignore_errors: True
   - name: install Code Blocks, Geany
     command: apt install -y codeblocks geany geany-plugins
   - name: install Atom
     command: apt install -y atom
     ignore_errors: True
   - name: install Sublime Text
     command: apt install -y sublime-text
     ignore_errors: True
   - name: install Scilab
     command: apt install -y scilab scilab-doc-pt-br scilab-plotlib scilab-ann scilab-celestlab python-sciscipy
   - name: install Dia
     command: apt install -y dia
   - name: install R
     command: apt install -y r-base r-base-dev
     ignore_errors: True
   - name: install Geogebra Classic
     command: apt install -y geogebra-classic
     ignore_errors: True
   - name: install dev utilities
     command: apt install -y graphviz vim obs-studio meld gdb cgdb valgrind pitivi sshfs bison flex wxmaxima
