---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  environment: "{{proxy_env}}"
  tasks:
   - name: restart Snapd
     service: name=snapd state=restarted
     ignore_errors: True
   - name: install Snap
     command: apt install -y snap
     ignore_errors: True
   - name: restart Snapd
     service: name=snapd state=restarted
   - name: install Snapcraft
     command: snap install --classic snapcraft
     ignore_errors: True
   - name: install NodeJS
     command: snap install --classic --channel=10 node
     ignore_errors: True
   - name: install Eclipse
     command: snap install --classic eclipse
     ignore_errors: True
   - name: install PyCharm-Community
     command: snap install --classic pycharm-community
     ignore_errors: True
