- block:
    - name: add a repository - {{ repository.name }}
      apt_repository:
        repo: "deb {{ repository.repo }}"
        state: present
        filename: "{{ repository.name }}"
    - name: add a signing key - {{ repository.name }}
      apt_key:
        url: "{{ repository.key_url }}"
        state: present
  rescue:
    - name: remove a repository - {{ repository.name }}
      apt_repository:
        repo: "deb {{ repository.repo }}"
        state: absent
        filename: "{{ repository.name }}"
