---
- hosts: dskDTL
  vars_files:
    - vars.yml
  tasks:
    - name: remove apt proxy config
      become: yes
      file:
        state: absent
        path: "{{ file_apt_proxy }}"
    - name: set apt proxy
      become: yes
      blockinfile:
        create: yes
        dest: "{{ file_apt_proxy }}"
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        content: |
          Acquire::http::Proxy "{{ proxy_env.http_proxy }}";
          Acquire::https::Proxy "{{ proxy_env.https_proxy }}";
          Acquire::ftp::Proxy "{{ proxy_env.ftp_proxy }}";
    - name: set snap proxy
      become: yes
      blockinfile:
        create: yes
        dest: "{{ item.fileproxy }}"
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        content: |
          [Service]
          Environment="{{ item.keyproxy }}={{ item.valueproxy }}"
      loop:
        - { fileproxy : "{{ file_snap_http_proxy }}", keyproxy : "http_proxy" , valueproxy : "{{ proxy_env.http_proxy }}" }
        #- { fileproxy : "{{ file_snap_https_proxy }}", keyproxy : "https_proxy" , valueproxy : "{{ proxy_env.https_proxy }}" }
        #- { fileproxy : "{{ file_snap_ftp_proxy }}", keyproxy : "ftp_proxy" , valueproxy : "{{ proxy_env.ftp_proxy }}" }
