---
- hosts: dskDTL
  vars_files:
    - vars.yml
  tasks:
    - name: show hostname before change
      debug: var=ansible_hostname
    - name: check that the /etc/cloud/cloud.cfg exists
      become: yes
      stat:
        path: /etc/cloud/cloud.cfg
      register: cloud_result
    - name: at cloud-init set 'preserve_hostname' from 'false' to 'true'
      become: yes
      copy:
        dest: /etc/cloud/cloud.cfg.d/99_hostname.cfg
        content: "preserve_hostname: true"
      when: cloud_result.stat.exists == True
    - name: change hostname with hostnamectl
      become: yes
      command: hostnamectl set-hostname "{{ inventory_hostname }}"
    - name: change hostname in /etc/hosts
      become: yes
      replace:
        path: /etc/hosts
        regexp: "^(127\\.0\\.1\\.1\\s+)\\S+$"
        replace: "\\1{{ inventory_hostname }}"
    - name: show hostname after change (before reboot)
      debug: var=ansible_hostname
    - name: reboot
      become: yes
      reboot:
      when: inventory_hostname != ansible_hostname
    - name: show hostname after change and after reboot
      debug: var=ansible_hostname
