---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: remove proxy installed
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/apt.conf.d/90curtin-aptproxy
        - /etc/systemd/system/snapd.service.d/snap_proxy.conf

