---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: remove previous proxy installed
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/apt/apt.conf.d/90curtin-aptproxy
        - /etc/systemd/system/snapd.service.d/snap_proxy.conf
    - name: remove previous proxy set
      lineinfile:
        path: /etc/apt/apt.conf
        state: absent
        regexp: 'Acquire.*Proxy'
