---
- hosts: dskDTL
  become: true
  vars_files:
    - vars.yml
  vars:
    mysql_cnf: "{{ ansible_env.HOME }}/.my.cnf"
    regex_pwd: 'password=(.*)'
    mysql_list_host_all:
      - 127.0.0.1
      - ::1
      - localhost
      - "{{ ansible_hostname }}"
      - "%"
  environment: "{{proxy_env}}"
  tasks:
#    - debug: var=hostvars
    - debug: var=inventory_hostname
    - debug: var=ansible_host
    - debug: var=ansible_hostname
#    - name: list
#      debug: msg="{{ item }}"
#      loop: "{{ mysql_list_host_all }}"
#    - debug: var=ansible_all_ipv4_addresses
#    - debug: var=ansible_default_ipv4.address
#    - debug: var=ansible_host
#    - debug: var=proxy_env
#    - debug: var=ssh_client_ipv4
#    - debug: var=proxy_env.http_proxy
#    - debug: var=ansible_lsb.codename
#    - debug: var=ansible_lsb.description
#    - debug: var=ansible_lsb.id
#    - debug: var=ansible_lsb.major_release
#    - debug: var=ansible_lsb.release
#    - debug: var=ansible_architecture
